// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyThdh2aDl7cZyOiNgvz0ItBx5GSq-4VQ',
    appId: '1:802175159405:web:1e8830de9f7117b8484364',
    messagingSenderId: '802175159405',
    projectId: 'barcode-scanner-9e70e',
    authDomain: 'barcode-scanner-9e70e.firebaseapp.com',
    storageBucket: 'barcode-scanner-9e70e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkPuQ1gVIKURH-x7Vi4rEggH_EgxvCmM',
    appId: '1:802175159405:android:02718cb27e4bb4b4484364',
    messagingSenderId: '802175159405',
    projectId: 'barcode-scanner-9e70e',
    storageBucket: 'barcode-scanner-9e70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7IPfB_D9R1BADQATuQOZrkpENkXNIbM',
    appId: '1:802175159405:ios:6a61e893191ba84b484364',
    messagingSenderId: '802175159405',
    projectId: 'barcode-scanner-9e70e',
    storageBucket: 'barcode-scanner-9e70e.appspot.com',
    iosClientId: '802175159405-s3uri1115qtgehmahbq0b1e46buls8vo.apps.googleusercontent.com',
    iosBundleId: 'de.markusbenz.barcodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7IPfB_D9R1BADQATuQOZrkpENkXNIbM',
    appId: '1:802175159405:ios:6a61e893191ba84b484364',
    messagingSenderId: '802175159405',
    projectId: 'barcode-scanner-9e70e',
    storageBucket: 'barcode-scanner-9e70e.appspot.com',
    iosClientId: '802175159405-s3uri1115qtgehmahbq0b1e46buls8vo.apps.googleusercontent.com',
    iosBundleId: 'de.markusbenz.barcodeScanner',
  );
}
